config/routes.rb
Rails.application.routes.draw do
  resources :customers, only: [:new, :create, :show, :update]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "customers#new"

  resources :customers do
    resources :products, only: %i[new create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :products
  validates :rfc, presence: true
  after_create :get_personal_data

  def full_name
    "#{first_name} #{last_name}"
  end

  private

  def get_personal_data
    CustomerInformation.new(self).save
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :customer
  validates_presence_of :quantity, :product, :unit_price
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def new
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def create
    @customer = Customer.create(rfc: 'AAA')
    redirect_to customer_path(@customer)
  end

  def update
    Customer.find(params[:id])
    redirect_to new_customer_path
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def create
    if customer.products.create(products_params)
      redirect_to customer_path(customer)
    else
      render :new
    end
  end

  private

  def products_params
    params.permit(products: [:quantity, :product, :unit_price, :amount]).require(:products)
  end

  def customer
    @customer ||= Customer.find params[:customer_id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/new.html.erb
<%= form_for(:customer, url: customers_path) do |f| %>
  <%= f.submit "Start app" %>
<% end %>

app/views/customers/show.html.erb
<h3>¡¡Hello <%= @customer.full_name %>!!</h3>
<p>Please complete all of the steps on this page:</p>
<ul>
  <li><%= link_to "Create An Invoice", new_customer_product_path(params[:id]) %></li>
</ul>
<%= form_for(:customer, url: customer_path, method: :put) do |f| %>
  <%= f.submit "Complete Process" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InterviewProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<div id="product-items" class="product-items" data-controller="product-item">
  <p>Item # <%= index %></p>
  <div>
    <%= label_tag "products[][quantity]", "Quantity:" %>
    <%= number_field_tag "products[][quantity]", nil,
      data: {
        action: "change->product-item#calculateAmount",
        product_item_target: "quantity"
      } %>
  </div>
  <div>
    <%= label_tag "products[][product]", "Product/Service:" %>
    <%= text_field_tag "products[][product]" %>
  </div>
  <div>
    <%= label_tag "products[][unit_price]", "Unit Price:" %>
    <%= number_field_tag "products[][unit_price]", nil,
      step: :any,
      data: {
        action: "change->product-item#calculateAmount",
        product_item_target: "unitPrice"
      } %>
  </div>
  <div>
    <%= label_tag "products[][amount]", "Amount:" %>
    <%= number_field_tag "products[][amount]", nil,
      class: "product_amounts",
      step: :any,
      data: {
        action:"update-amounts@window->product-form#calculateSubTotal",
        product_item_target: "amount"
      } %>
  </div>
</div>

app/views/products/new.html.erb
Please add your products and click on Create:

<%= form_tag(customer_products_path, remote: true, id: "product-form", data: { controller: "product-form" }) do |f| %>
  <% (1..2).each do |i| %>
    <%= render partial: "form",
      locals: {
        index: i
      }
    %>
  <% end %>
  <br>
  <div>
    <strong>Sub Total: </strong><span data-product-form-target="subtotal">0</span>
  </div>
  <div>
    <strong>Tax: </strong><span data-product-form-target="tax">0</span>
  </div>
  <div>
    <strong>Total: </strong><span data-product-form-target="total">0</span>
  </div>
  <div>
    <span class="msg-amount" data-product-form-target="amountMessage"></span>
  </div>
  <%= submit_tag "Create" %>
<% end %>